version: 0.0
os: linux
files:
  - source: /app
    destination: /var/www/html
permissions:
  - object: /
    pattern: "**"
    owner: root
    group: root
hooks:
  ApplicationStop:
    - location: scripts/ApplicationStop.sh
      timeout: 120
      runas: root
  BeforeInstall:
    - location: scripts/BeforeInstall.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/AfterInstall.sh
      timeout: 30
      runas: root
  ApplicationStart:
    - location: scripts/ApplicationStart.sh
      timeout: 120
      runas: root